# start symfony-api project
all:
	php -S localhost:3000

api-start:
	cd Api && \
    symfony server:start

server-stop:
	cd Api && \
    symfony server:stop

build:
	cd Api && \
    $(MAKE) build

update:
	cd Api && \
    $(MAKE) update